export const CONFIG={
 APP_NAME:'TRIPLE-F EDUCATION LMS',
 SUPABASE_URL:'https://hysvldqcltxmnthbgyyv.supabase.co',
 SUPABASE_ANON_KEY:'sb_publishable_fsT_h8MmYMVJcfN2-fAABw_Ec8qQTtp',
 DRIVE_API_URL:'PASTE_GOOGLE_APPS_SCRIPT_WEB_APP_URL_HERE',
 ACCOUNT_API_URL:'PASTE_SUPABASE_EDGE_FUNCTION_URL_HERE',
 SCHOOL_NAME:'TRIPLE-F EDUCATION',
 WHATSAPP_COUNTRY:'62'
};
