export const CONFIG={
 APP_NAME:'TRIPLE-F EDUCATION LMS',
 SUPABASE_URL:'PASTE_SUPABASE_URL_HERE',
 SUPABASE_ANON_KEY:'PASTE_SUPABASE_ANON_KEY_HERE',
 DRIVE_API_URL:'PASTE_GOOGLE_APPS_SCRIPT_WEB_APP_URL_HERE',
 ACCOUNT_API_URL:'PASTE_SUPABASE_EDGE_FUNCTION_URL_HERE',
 SCHOOL_NAME:'TRIPLE-F EDUCATION',
 WHATSAPP_COUNTRY:'62'
};
