/** TRIPLE-F EDUCATION - Google Drive Gateway
 * Deploy: Deploy > New deployment > Web app > Execute as Me > Who has access: Anyone.
 * Set Script Property DRIVE_ROOT_FOLDER_ID to the ID of your root Drive folder.
 * This endpoint is intentionally simple. Never put Google credentials in GitHub.
 */
function json_(o){return ContentService.createTextOutput(JSON.stringify(o)).setMimeType(ContentService.MimeType.JSON)}
function root_(){var id=PropertiesService.getScriptProperties().getProperty('DRIVE_ROOT_FOLDER_ID');if(!id)throw new Error('DRIVE_ROOT_FOLDER_ID belum diisi');return DriveApp.getFolderById(id)}
function folder_(name){var r=root_(),it=r.getFoldersByName(name);return it.hasNext()?it.next():r.createFolder(name)}
function doGet(e){return json_({ok:true,service:'TRIPLE-F EDUCATION Drive Gateway',time:new Date().toISOString()})}
function doPost(e){try{var p=e&&e.parameter?e.parameter:{};var action=p.action||'ping';if(action==='ping')return json_({ok:true});if(action==='upload'){var folder=folder_(p.folder||'01_MATERI');var bytes=Utilities.base64Decode(p.base64);var blob=Utilities.newBlob(bytes,p.mime||'application/octet-stream',p.filename||('file-'+Date.now()));var file=folder.createFile(blob);file.setSharing(DriveApp.Access.ANYONE_WITH_LINK,DriveApp.Permission.VIEW);return json_({ok:true,id:file.getId(),name:file.getName(),url:'https://drive.google.com/file/d/'+file.getId()+'/view'});}if(action==='report_pdf'){var folder=folder_('06_LAPORAN');var html=Utilities.newBlob(Utilities.base64Decode(p.htmlBase64||''),'text/html','report.html');var f=folder.createFile(html).getAs(MimeType.PDF);var file=folder.createFile(f).setName(p.filename||('Laporan-'+Date.now()+'.pdf'));file.setSharing(DriveApp.Access.ANYONE_WITH_LINK,DriveApp.Permission.VIEW);return json_({ok:true,id:file.getId(),url:'https://drive.google.com/file/d/'+file.getId()+'/view'});}if(action==='delete'){DriveApp.getFileById(p.fileId).setTrashed(true);return json_({ok:true});}return json_({ok:false,error:'Unknown action'});}catch(err){return json_({ok:false,error:String(err)})}}
